name: Build and release (linux, macos)

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build (linux)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build (release)
        run: cargo build --release

      - name: Package linux binary
        run: |
          mkdir -p out
          cp target/release/pano out/pano
          chmod +x out/pano
          tar -czf pano-linux-x86_64.tar.gz -C out pano

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: pano-linux-x86_64
          path: pano-linux-x86_64.tar.gz

  build-macos:
    name: Build (macos)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build (release)
        run: cargo build --release

      - name: Package macos binary
        run: |
          mkdir -p out
          cp target/release/pano out/pano
          chmod +x out/pano
          zip -r pano-macos-x86_64.zip out/pano

      - name: Upload macos artifact
        uses: actions/upload-artifact@v4
        with:
          name: pano-macos-x86_64
          path: pano-macos-x86_64.zip

  create_release:
    name: Create GitHub Release and upload assets
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos]
    if: startsWith(github.ref, 'refs/tags/') # only run on tag pushes
    steps:
      - uses: actions/checkout@v4

      - name: Download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: pano-linux-x86_64
          path: artifacts

      - name: Download macos artifact
        uses: actions/download-artifact@v4
        with:
          name: pano-macos-x86_64
          path: artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload linux asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/pano-linux-x86_64.tar.gz
          asset_name: pano-linux-x86_64.tar.gz
          asset_content_type: application/gzip

      - name: Upload macos asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/pano-macos-x86_64.zip
          asset_name: pano-macos-x86_64.zip
          asset_content_type: application/zip
