[package]
name = "pano"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
tao = "0.31.1"
wry = { version = "0.48.1", features = ["transparent"] }

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=-crt-static"]
