[package]
name = "pano"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
tao = "0.34.2"
wry = { version = "0.53.3", features = ["transparent"] }
