name: Build

on:
  push:
    tags: ['v*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  build:
    name: Build ${{ matrix.variant }}
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        include:
          - dockerfile: images/glibc.dockerfile
            variant: glibc
          - dockerfile: images/musl.dockerfile
            variant: musl
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and extract binaries
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          outputs: type=local,dest=./output
          cache-from: type=gha,scope=${{ matrix.variant }}
          cache-to: type=gha,mode=max,scope=${{ matrix.variant }}

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          load: false
          tags: pano-${{ matrix.variant }}:latest
          cache-from: type=gha,scope=${{ matrix.variant }}
          outputs: type=docker,dest=./pano-${{ matrix.variant }}.tar

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ matrix.variant }}
          path: output/

      - name: Upload image artifacts
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ matrix.variant }}
          path: pano-${{ matrix.variant }}.tar
